repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-yaml
        args: ['--unsafe']
        exclude: .github/workflows/java-ci-with-maven.yml